services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.production  # Use .env.production for production deployments
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
