version: 1
services:
  - type: web
    name: collection-log-backend
    env: docker
    plan: free
    buildContext: ./backend
    dockerfilePath: Dockerfile
    ports:
      - port: 8000

  - type: web
    name: collection-log-frontend
    env: docker
    plan: free
    buildContext: ./frontend
    dockerfilePath: Dockerfile
    ports:
      - port: 3000
