# Generated by Django 5.1.2 on 2024-10-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('activity_name', models.CharField(max_length=255)),
                ('completions_per_hour_main', models.FloatField()),
                ('completions_per_hour_iron', models.FloatField()),
                ('extra_time_to_first_completion', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verification_source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('obtained', models.BooleanField(default=False)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompletionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField()),
                ('requires_previous', models.BooleanField()),
                ('active', models.BooleanField()),
                ('exact', models.BooleanField()),
                ('independent', models.BooleanField()),
                ('drop_rate_attempts', models.FloatField()),
                ('e_and_i', models.CharField(blank=True, max_length=255, null=True)),
                ('e_only', models.CharField(blank=True, max_length=255, null=True)),
                ('i_only', models.CharField(blank=True, max_length=255, null=True)),
                ('neither_inverse', models.FloatField(blank=True, null=True)),
                ('completion_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='log_importer.completionrate')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_importer.item')),
            ],
        ),
        migrations.CreateModel(
            name='KillCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('sequence', models.IntegerField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killcounts', to='log_importer.logentry')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='log_importer.logentry'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='log_importer.tab'),
        ),
    ]
