# Generated by Django 5.1.2 on 2024-10-25 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_importer.item')),
            ],
        ),
    ]
