# Generated by Django 5.1.2 on 2024-10-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_importer', '0002_remove_activitymap_activity_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymap',
            name='completed',
        ),
    ]
